import { Button, Layout, Skeleton, Result } from "antd";
import { Content, Footer, Header } from "antd/lib/layout/layout";
import Title from "antd/lib/typography/Title";
import Head from "next/head";
import { Router, useRouter } from "next/router";
import useSWR from "swr";
import Login from "../components/login";
import inspirecloud from "../services/inspirecloud";
import styles from "../styles/Home.module.less";
import Reviewer from "./../components/reviewer";

export default function Home() {
  const { data, error } = useSWR("getUserInfo", (name) =>
    inspirecloud.run(name)
  );
  if (error)
    return (
      <Result
        status="500"
        title="500"
        subTitle="Sorry, something went wrong."
        extra={
          <Button
            type="primary"
            onClick={(e) => {
              e.preventDefault();
              location.reload();
            }}
          >
            重试
          </Button>
        }
      />
    );
  if (!data) return <Skeleton active />;
  const success = data.success;
  if (success) return <Reviewer userInfo={data.user} />;
  else
    return (
      <div className={styles["container"]}>
        <Head>
          <title>Reviewer</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          <Header className={styles["header"]} />
          <Content className={styles["main"]}>
            <Title> 欢迎使用 Reviewer</Title>
            <Login />
            <div className={styles["main_pwrapper"]}>
              <p>
                Reviewer
                是一个旨在通过运用爱斯宾好遗忘曲线帮助使用者更好复习所学内容的应用
              </p>
              <p>
                使用者在登录之后可以查看今日所需完成的任务，并根据今日所学内容添加新任务
              </p>
              <p>
                添加的新任务分别会在1天，1周，1月后出现在你的任务清单上，以帮助你回忆遗忘的内容
              </p>
            </div>
          </Content>
          <Footer style={{ textAlign: "center" }}>
            Reviewer ©2022 Created by dyhes
          </Footer>
        </Layout>
      </div>
    );
}
